---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-cfcli
    tag: "latest"


inputs:
  - name: git-repo

run:
  path: bash
  args:
    - -exc
    - |
      cf install-plugin do-all -r "CF-Community"
      cf install-plugin -r CF-Community "bg-restage"
      cf login -u {{CF_USER}} -p {{CF_PASS}} -a {{CF_API}} -o {{CF_ORG}} -s {{CF_SPACE}}
      cf do-all bg-restage {}