---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: greent/ubuntu
    tag: "latest"

inputs:
- name: git-repo

run:
  path: git-repo/ci/scripts/kong-service.sh

params:
  ROUTE:
  DOMAIN:
  GW_DOMAIN:
  ADMIN_API: