---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

inputs:
  - name: git-repo
  - name: release-candidate

outputs:
  - name: image-build-dir

run:
  path: git-repo/ci/scripts/merge-directories.sh
